[package]
name = "data_vault_exxx"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
indicatif = "0.17.3"
termion = "2.0.1"
rand_core = "0.6.4"
rand = "0.8.5"
