[package]
name = "gitMap"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "3.3.2"
reqwest = "0.11.4"
serde = "1.0.130"
serde_json = "1.0.64"
actix-rt = "2.4.1"
tokio = { version = "1", features = ["full"] }
