[package]
name = "zip_cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = "2.1.6"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
crypto = "0.5.1"
rand = "0.8.5"
rng = "0.1.0"
